name: TweetsSentimentAnalysis
save_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/models/1/TSModel.hdf5
ckpt_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/models/ckpt/TSModel.hdf5
onnx_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/models/1/TSModel.onnx
history_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/evaluation/
vectorize_layer_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/models/1/vectorize_layer

Train_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/Data/Train data.csv
Test_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/Data/Test data.csv
Val_path: C:/Users/HI/Desktop/.dev/python/Deep learning/Projects/TweetsSentimentAnalysis/Data/Validation data.csv
load_with_info: False

